export const ADD_APPETIZER='ADD_APPETIZER';
export const SHOW_APPETIZERS='SHOW_APPETIZERS';
export const SHOW_APPETIZER='SHOW_APPETIZER';
export const EDIT_APPETIZER='EDIT_APPETIZER';
export const DELETE_APPETIZER='DELETE_APPETIZER';