export const SHOW_MAIN_COURSES='SHOW_MAIN_COURSES';
export const ADD_MAIN_COURSE='ADD_MAIN_COURSE';
export const DELETE_MAIN_COURSE='DELETE_MAIN_COURSE';
export const SHOW_MAIN_COURSE='SHOW_MAIN_COURSE';
export const EDIT_MAIN_COURSE='EDIT_MAIN_COURSE';